# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_additional_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона дополнительный'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_additional_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона дополнительный'),
        ),
    ]
