# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
    ]
