# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20170411_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='phone_mobile',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='birth_day',
            field=models.DateField(null=True, verbose_name='День рожденья'),
        ),
    ]
