# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20170411_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='phone_mobile',
            field=models.IntegerField(null=True, verbose_name='Мобильный телефон'),
        ),
    ]
