# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employe_work_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает?'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='specialty',
            field=models.CharField(max_length=50, verbose_name='Специализация сотрудника'),
        ),
    ]
