# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20170602_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='is_head',
            field=models.BooleanField(default=True, verbose_name='Главный врач?'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото врача'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='Специализация сотрудника'),
        ),
    ]
