# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20170602_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='candidate_of_medical_sciences',
            field=models.BooleanField(default=False, verbose_name='Кандидат медицинских наук?'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='День рожденья'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Биографические сведения'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone_mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='work_with',
            field=models.DateField(blank=True, null=True, verbose_name='Поступил на работу'),
        ),
    ]
