# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmd_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Выводить на сайт?')),
                ('id_item', models.IntegerField(default=0, verbose_name='Идентификатор группы по прайсу CMD')),
                ('group_title', models.CharField(max_length=255, verbose_name='Заголовок группы иследований')),
                ('parent_group', models.IntegerField(default=0, verbose_name='Родитель группы')),
            ],
            options={
                'verbose_name': 'Исследование | Анализ | CMD',
                'verbose_name_plural': 'Исследования | Анализы | CMD',
            },
        ),
        migrations.CreateModel(
            name='cmd_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Выводить на сайт?')),
                ('id_item', models.IntegerField(default=0, verbose_name='Идентификатор услуги по прайсу CMD')),
                ('cmd_url', models.CharField(max_length=255, verbose_name='Ссылка на описание cmd сайт')),
                ('item_title', models.CharField(max_length=255, verbose_name='Идентификатор ссылки')),
                ('price_doctor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена для доктора')),
                ('price_cmd', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена у CMD')),
                ('description', models.TextField(blank=True, verbose_name='О исследовании')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmd_data.cmd_groups', verbose_name='Группа исследования')),
            ],
            options={
                'verbose_name': 'Исследование | Анализ | CMD',
                'verbose_name_plural': 'Исследования | Анализы | CMD',
            },
        ),
    ]
