# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd_data', '0007_remove_cmd_items_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmd_groups',
            options={'verbose_name': 'Группа исследований | CMD', 'verbose_name_plural': 'Группы исследований | CMD'},
        ),
        migrations.AlterField(
            model_name='cmd_items',
            name='id_item',
            field=models.CharField(default='0', max_length=255, verbose_name='Идентификатор услуги по прайсу CMD'),
        ),
    ]
