# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd_data', '0009_auto_20180420_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmd_items',
            name='id_item',
            field=models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='Идентификатор услуги по прайсу CMD'),
        ),
    ]
