# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd_data', '0010_auto_20180420_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmd_items',
            name='id_item',
            field=models.IntegerField(default=0, verbose_name='Идентификатор услуги по прайсу CMD'),
        ),
    ]
