# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd_data', '0011_auto_20180420_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmd_items',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О исследовании'),
        ),
        migrations.AlterField(
            model_name='cmd_items',
            name='id_item',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор услуги по прайсу CMD'),
        ),
        migrations.AlterField(
            model_name='cmd_items',
            name='item_title',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор ссылки'),
        ),
    ]
