# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('add_to_group', models.CharField(blank=True, max_length=20, verbose_name='Дополнительно загружать услугу в группы')),
                ('price_from', models.IntegerField(null=True, verbose_name='Цена от')),
                ('price_to', models.IntegerField(blank=True, null=True, verbose_name='Цена до')),
                ('to_order', models.BooleanField(default=False, verbose_name='Тербуется предварительный заказ')),
                ('service_time', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность услуги')),
                ('manufacturer_country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна производитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='service_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы услуг')),
                ('specialist_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название специалиста')),
                ('is_main', models.BooleanField(default=False, verbose_name='Выводить группу на главную страницу раздела')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить в категории на сайт?')),
                ('group_description', models.TextField(blank=True, verbose_name='Информация относящаяся ко всей группе')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка категории ')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service_group', verbose_name='Название группы услуг'),
        ),
    ]
