# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='add_to_group',
            field=models.IntegerField(blank=True, verbose_name='Дополнительно загружать услугу в группы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service_group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы услуг'),
        ),
        migrations.AlterField(
            model_name='service_group',
            name='specialist_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название для главной'),
        ),
    ]
