# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170601_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='add_to_group',
            field=models.IntegerField(null=True, verbose_name='Дополнительно загружать услугу в группы'),
        ),
    ]
