# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invitro_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=255)),
                ('slug', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='invitro_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('slug', models.URLField()),
                ('preparation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('result_interpretation', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitro_data.invitro_group')),
            ],
        ),
        migrations.CreateModel(
            name='invitro_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_title', models.CharField(max_length=255)),
                ('slug', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='invitro_group',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitro_data.invitro_profile'),
        ),
    ]
