# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitro_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitro_base_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.URLField(verbose_name='Базовый URL')),
            ],
            options={
                'verbose_name': 'Базовый URL',
                'verbose_name_plural': 'Базовый URL',
            },
        ),
        migrations.AlterModelOptions(
            name='invitro_group',
            options={'verbose_name': 'Узкая группа исследования', 'verbose_name_plural': 'Узкие группы исследований'},
        ),
        migrations.AlterModelOptions(
            name='invitro_items',
            options={'verbose_name': 'Исследование | Анализ', 'verbose_name_plural': 'Исследования | Анализы'},
        ),
        migrations.AlterModelOptions(
            name='invitro_profile',
            options={'verbose_name': 'Глобальная группа исследования', 'verbose_name_plural': 'Глобальные группы исследований'},
        ),
        migrations.AddField(
            model_name='invitro_items',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
