# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitro_data', '0003_auto_20170403_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitro_profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='invitro_profile',
            name='slug_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
