# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitro_data', '0004_auto_20170403_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitro_items',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='invitro_items',
            name='result_interpretation',
        ),
    ]
