# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitro_data', '0005_auto_20170404_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitro_group',
            name='group_title',
            field=models.CharField(max_length=255, verbose_name='Имя группы исследований'),
        ),
        migrations.AlterField(
            model_name='invitro_group',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitro_data.invitro_profile', verbose_name='Профиль исследований'),
        ),
        migrations.AlterField(
            model_name='invitro_group',
            name='slug_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Идентификатор ссылки'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='analysis_name',
            field=models.CharField(max_length=255, verbose_name='Идентификатор ссылки'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Идентификатор анализа'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='description',
            field=models.CharField(blank=True, max_length=50000, verbose_name='О исследовании'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitro_data.invitro_group', verbose_name='Название исследования'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='invitro_items',
            name='slug_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Идентификатор ссылки'),
        ),
        migrations.AlterField(
            model_name='invitro_profile',
            name='profile_title',
            field=models.CharField(max_length=255, verbose_name='Профиль исследований'),
        ),
        migrations.AlterField(
            model_name='invitro_profile',
            name='slug_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Идентификатор ссылки'),
        ),
    ]
