# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitro_data', '0006_auto_20170410_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitro_items',
            name='description',
            field=models.TextField(blank=True, verbose_name='О исследовании'),
        ),
    ]
