# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_settings',
            name='proxy_enable',
            field=models.BooleanField(default=False, verbose_name='Активный прокси'),
        ),
    ]
